/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package circuitdesigner;

/**
 *
 * @author marco
 */
public class Info_Window extends javax.swing.JFrame {

    /**
     * Creates new form Info_Window
     */
    public Info_Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Canva_Acerca = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txt_Info = new javax.swing.JTextArea();
        Boton_Atrás = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(4, 6, 6));
        setName("Acerca de este Software"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(600, 900));

        Canva_Acerca.setBackground(new java.awt.Color(144, 221, 208));
        Canva_Acerca.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Txt_Info.setEditable(false);
        Txt_Info.setBackground(new java.awt.Color(254, 254, 254));
        Txt_Info.setColumns(20);
        Txt_Info.setFont(new java.awt.Font("FreeSerif", 1, 18)); // NOI18N
        Txt_Info.setForeground(new java.awt.Color(97, 172, 213));
        Txt_Info.setRows(5);
        Txt_Info.setText("      Instituto Tecnológico de Costa Rica.\n\n     Algoritmos y Estructuras de Datos I.\n\n             Proyecto Programado Uno:\n\n                    Circuit Designer.\n\n                          Profesor:\n\n                     Antonio Torres.\n\n                          Alumno:\n\n                     Marco Picado M.\n\n                           Versión: \n\n                              0.5.5");
        jScrollPane1.setViewportView(Txt_Info);

        Boton_Atrás.setBackground(new java.awt.Color(27, 11, 11));
        Boton_Atrás.setFont(new java.awt.Font("Garuda", 1, 14)); // NOI18N
        Boton_Atrás.setForeground(new java.awt.Color(223, 77, 77));
        Boton_Atrás.setText("Atrás");
        Boton_Atrás.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(192, 14, 14), 3, true));
        Boton_Atrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AtrásActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Canva_AcercaLayout = new javax.swing.GroupLayout(Canva_Acerca);
        Canva_Acerca.setLayout(Canva_AcercaLayout);
        Canva_AcercaLayout.setHorizontalGroup(
            Canva_AcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Canva_AcercaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Canva_AcercaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Boton_Atrás, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        Canva_AcercaLayout.setVerticalGroup(
            Canva_AcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Canva_AcercaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Boton_Atrás)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Canva_Acerca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Canva_Acerca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_AtrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AtrásActionPerformed
        
        this.setVisible(false);
        
        this.dispose();
        
    }//GEN-LAST:event_Boton_AtrásActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Atrás;
    private javax.swing.JPanel Canva_Acerca;
    private javax.swing.JTextArea Txt_Info;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
