/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package circuitdesigner;

/**
 *
 * @author marco
 */
public class Window_Circuit extends javax.swing.JFrame {

    /**
     * Creates new form Window_Circuit
     */
    public Window_Circuit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Canva_circuit = new javax.swing.JPanel();
        Pallete_Canva = new javax.swing.JLayeredPane();
        Etiq_Pallete = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 900));
        setResizable(false);

        Canva_circuit.setBackground(new java.awt.Color(243, 253, 252));
        Canva_circuit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Circuit Designer by Marco Picado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(6, 4, 237))); // NOI18N

        Pallete_Canva.setBackground(new java.awt.Color(166, 236, 229));
        Pallete_Canva.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 174, 221), 3, true));
        Pallete_Canva.setForeground(new java.awt.Color(159, 149, 149));
        Pallete_Canva.setAutoscrolls(true);

        javax.swing.GroupLayout Pallete_CanvaLayout = new javax.swing.GroupLayout(Pallete_Canva);
        Pallete_Canva.setLayout(Pallete_CanvaLayout);
        Pallete_CanvaLayout.setHorizontalGroup(
            Pallete_CanvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Pallete_CanvaLayout.setVerticalGroup(
            Pallete_CanvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        Etiq_Pallete.setBackground(new java.awt.Color(68, 208, 184));
        Etiq_Pallete.setFont(new java.awt.Font("Garuda", 2, 12)); // NOI18N
        Etiq_Pallete.setForeground(new java.awt.Color(1, 1, 1));
        Etiq_Pallete.setText("PALETE");

        javax.swing.GroupLayout Canva_circuitLayout = new javax.swing.GroupLayout(Canva_circuit);
        Canva_circuit.setLayout(Canva_circuitLayout);
        Canva_circuitLayout.setHorizontalGroup(
            Canva_circuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Canva_circuitLayout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addGroup(Canva_circuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pallete_Canva)
                    .addComponent(Etiq_Pallete, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
        );
        Canva_circuitLayout.setVerticalGroup(
            Canva_circuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Canva_circuitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Etiq_Pallete)
                .addGap(18, 18, 18)
                .addComponent(Pallete_Canva))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Canva_circuit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Canva_circuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_Circuit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_Circuit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_Circuit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_Circuit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_Circuit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Canva_circuit;
    private javax.swing.JLabel Etiq_Pallete;
    private javax.swing.JLayeredPane Pallete_Canva;
    // End of variables declaration//GEN-END:variables
}
